<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>BL</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="BlApi\Factory.cs" />
    <Compile Include="BlApi\IBl.cs" />
    <Compile Include="BlApi\ICustomer.cs" />
    <Compile Include="BlApi\IProduct.cs" />
    <Compile Include="BlApi\ISale.cs" />
    <Compile Include="BlApi\IOrder.cs" />
    <Compile Include="BlImplementation\Bl.cs" />
    <Compile Include="BlImplementation\CustomerImplementation.cs" />
    <Compile Include="BlImplementation\ProductImplementation.cs" />
    <Compile Include="BlImplementation\SaleImplementation.cs" />
    <Compile Include="BlImplementation\OrderImplementation.cs" />
    <Compile Include="BO\Customer.cs" />
    <Compile Include="BO\Enums.cs" />
    <Compile Include="BO\Product.cs" />
    <Compile Include="BO\Sale.cs" />
    <Compile Include="BO\SaleInProduct.cs" />
    <Compile Include="BO\Order.cs" />
    <Compile Include="BO\ProductInOrder.cs" />
    <Compile Include="BO\Exceptions.cs" />
    <Compile Include="BO\Tools.cs" />
    <Compile Include="Class1.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DalFacade\DalFacade.csproj" />
    <ProjectReference Include="..\DalList\DalList.csproj" />
  </ItemGroup>
</Project>
