<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
 <TargetFramework>net9.0-windows</TargetFramework>
 <UseWindowsForms>true</UseWindowsForms>
 <ImplicitUsings>enable</ImplicitUsings>
 <Nullable>enable</Nullable>
 <OutputType>WinExe</OutputType>
 <RootNamespace>UI</RootNamespace>
 </PropertyGroup>
 <ItemGroup>
 <ProjectReference Include="..\BL\BL.csproj" />
 <ProjectReference Include="..\DalList\DalList.csproj" />
 <ProjectReference Include="..\DalXml\DalXml.csproj" />
 </ItemGroup>
</Project>